name: Expo Free Cloud Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Upgrade EAS CLI Tool
        run: npm install -g eas-cli

      - name: Setup EAS Authenticator
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install Project Dependencies
        run: npm install

      - name: Trigger Local EAS Build
        run: eas build --platform android --profile production --local --non-interactive --output=./swayv-production.apk


      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: swayv-production-apk
          path: ./swayv-production.apk
